# Generated by Django 4.2.3 on 2023-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_user',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
