# Generated by Django 4.2.3 on 2023-08-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_trip_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_charge',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
